# nav2_params.yaml

# amcl:
#   ros__parameters:
#     use_map_topic: true
#     scan_topic: /scan
#     odom_topic: /odom
#     base_frame_id: base_link
#     map_frame_id: map
#     global_frame_id: map

controller_server:
  ros__parameters:
    controller_frequency: 20.0
    max_vel_x: 0.5
    min_vel_x: 0.1
    max_rot_vel: 1.0
    min_rot_vel: 0.2
    use_sim_time: false

planner_server:
  ros__parameters:
    planner_frequency: 1.0
    max_planning_time: 1.0
    tolerance: 0.2
    use_sim_time: false

costmap:
  global_costmap:
    ros__parameters:
      global_frame: map             # 显示全局地图的参考系
      robot_base_frame: base_link  # 机器人底座坐标系
      map_topic: /map
      robot_radius: 0.3
      resolution: 0.05
      footprint: [[0.3, 0.3], [-0.3, 0.3], [-0.3, -0.3], [0.3, -0.3]]
      use_sim_time: false
      always_send_full_costmap: true

  local_costmap:
    ros__parameters:
      global_frame: odom           # 局部地图在 odom 坐标系下
      robot_base_frame: base_link
      map_topic: /map
      robot_radius: 0.3
      resolution: 0.05
      footprint: [[0.3, 0.3], [-0.3, 0.3], [-0.3, -0.3], [0.3, -0.3]]
      use_sim_time: false
      always_send_full_costmap: true
